haproxy:
  image: eeacms/haproxy
    io.rancher.scheduler.affinity:host_label: eni-seis=yes
  links:
  - plone
  environment:
  - BACKENDS=plone
  - BACKENDS_PORT=8080
  - DNS_ENABLED=true
  volumes:
  - /etc/localtime:/etc/localtime:ro

memcached:
  image: eeacms/memcached
  environment:
  - MEMCACHED_MEMORY=2048
  labels:
    io.rancher.scheduler.affinity:host_label: eni-seis=yes

postfix:
  image: eeacms/postfix:eionet
  labels:
    io.rancher.scheduler.affinity:host_label: eni-seis=yes
  environment:
  - MTP_HOST=eni-seis.eionet.europa.eu
  - MTP_USER=${POSTFIX_USER}
  - MTP_PASS=${POSTFIX_PASS}
  volumes:
  - /etc/localtime:/etc/localtime:ro

plone:
  image: eeacms/plone-eni-seis:2016.10.11
  labels:
    io.rancher.scheduler.affinity:host_label: eni-seis=yes
  links:
  - zeoserver
  - memcached
  - postfix
  environment:
    ZOPE_MODE: zeo_client
  volumes:
  - /etc/localtime:/etc/localtime:ro

async:
  image: eeacms/plone-eni-seis:2016.10.11
  labels:
    io.rancher.scheduler.affinity:host_label: eni-seis=yes
  links:
  - zeoserver
  - memcached
  - postfix
  environment:
  - ZOPE_MODE=zeo_async
  volumes:
  - /etc/localtime:/etc/localtime:ro

zeoserver:
  image: eeacms/plone-eni-seis:2016.10.11
  labels:
    io.rancher.sidekicks: data
    io.rancher.scheduler.affinity:host_label: eni-seis-data=yes
  volumes_from:
  - data
  environment:
  - ZOPE_MODE=zeoserver
  volumes:
  - /etc/localtime:/etc/localtime:ro

data:
  image: busybox
  labels:
    io.rancher.container.start_once: 'true'
  tty: true
  stdin_open: true
  volumes:
  - ${filestorage}:/data/filestorage
  - ${blobstorage}:/data/blobstorage
  command: ["chown", "-R", "500:500", "/data"]
