plone:
  image: eeacms/plone-eni-seis:devel
  ports:
  - "8080:8080"
  - "4444:4444"
  links:
  - memcached:memcached
  - postfix:postfix
  volumes:
  - ./src:/plone/instance/src
  - eni-seis-data:/data
  command: ["fg"]

memcached:
  image: eeacms/memcached
  environment:
  - MEMCACHED_MEMORY=2048

postfix:
  image: eeacms/postfix
  environment:
  - MTP_HOST=devel.eni-seis.eionet.europa.eu
